# Generated by Django 3.1.7 on 2021-04-12 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('t', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='edge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('n1', models.CharField(max_length=100)),
                ('n2', models.CharField(max_length=100)),
                ('minute', models.IntegerField()),
                ('cost', models.IntegerField()),
            ],
        ),
    ]
